### ISSUE TITLE
Allow admins to completely disable shortcode queries

### ISSUE THREAD

**Issue by hughbris** [finanalyst/grav-plugin-sqlite#11]
This plugin allows us to disable `[sql-table]` shortcode select queries per page or to globally enable them.

Since editors can edit page headers, it would be nice to prevent them from running queries at all from page markdown.

I don't think it's a gaping security problem (as long as you trust your editors), but it seems a logical extension to the settings already available.

**Comment by finanalyst** [comment]
@hughbris  Working through all issues. On this one, have you any suggestions about how to do this. The shortcode enabling global/per-page is copied from other shortcode modules.   
Not quite sure where you would want the constraint to be made, or how this would differ from allowing select queries per page.
Happy to incorporate with some guidance as to what is wanted.

**Comment by finanalyst** [comment]
PR by @hughbris handled this.
