### ISSUE TITLE
Stopping redirects?

### ISSUE THREAD

**Issue by dlannan** [finanalyst/grav-plugin-sqlite#12]
Im wondering if there is a way to submit the form, without redirecting to a new page?
I think it would require an ajax submit, and "preventDefault" call within a function. Ive tried a few ways so far, but if there are any suggestions how this could be done (if it can) that would be great.
Im thinking of adding a page variable that would control this (I think this would be most useful).

**Comment by hughbris** [comment]
FWIW I suspect this issue is a better fit for the Form plugin.

**Comment by finanalyst** [comment]
Agree with hughbris
