### ISSUE TITLE
is this plugin abandoned?

### ISSUE THREAD

**Issue by hughbris** [finanalyst/grav-plugin-sqlite#13]
Hi, I don't particularly want to take this plugin over, but it's been some time since the owner @finanalyst has responded to some issues or [my PR](https://github.com/finanalyst/grav-plugin-sqlite/pull/10), so I need to politely check if it is being maintained in accordance with the [Abandoned Resource Protocol](https://learn.getgrav.org/16/advanced/grav-development#abandoned-resource-protocol).

I have several other improvements in local branches I'd also like to have considered for official integration.

Really appreciating the plugin, BTW :) Thank you for building it.

Cheers

**Comment by finanalyst** [comment]
@hughbris  Sorry for incredibly long delay. Have you taken it over?
I cannot get GIt to send me emails.

**Comment by hughbris** [comment]
Thanks for integrating all these changes and inviting me as a collaborator.

I've simply been maintaining and using [my own fork](https://github.com/hughbris/grav-plugin-sqlite) because I've become used to doing things that way from a few other plugins where changes I need haven't been integrated for any number of reasons.

The other reason, if memory serves, is that I had plans to broaden this to support PostGreSQL and possibly other DB providers, which suggests a new broader name and possibly a significant refactor.

There are other desirable tweaks I have in a note somewhere. I won't dig that out or address your questions in other issues right now, too busy! Good to see you back looking at this. I wish I could help you get your notifications.
