### ISSUE TITLE
Grav skeleton

### ISSUE THREAD

**Issue by covecove1** [finanalyst/grav-plugin-sqlite#2]
Hello, 

I would like to ask you to make a simple skeleton which utilizes SQLite plugin as an example, or an explanation as to how to edit specific table row.

For example,

a table in which every row has edit button, and when it is pressed it opens corresponding row according to it's id(row-id?) to be edited.

Thank You in advance!

**Comment by finanalyst** [comment]
I have added another example to the documentation. It is for a page on a website I developed. 
The example does not do quite what you want, but it shows how to get data from a database, transfer it from the html table element to a Form, and then use sql-update to send the information back to the web site. I also use the datatables plugin to manipulate the table.

**Comment by covecove1** [comment]
Thank You very much. This plugin is great. 
Did You try to use adminer for MySQL with GRAV? It's pretty nice, and it can be used as a business webapp with Adminer Editor. :)

**Comment by finanalyst** [comment]
Thanks. I use `phpliteadmin` (it seems similar to phpMyAdmin and adminer) and put it in a directory where I can access the sqlite database. There is no need to make a GRAV plugin to do this.
But I don't want to give most users the power of a full database management system. I want to set up the database, and allow for some users to add/modify the data.
