### ISSUE TITLE
Shortcode 'id' parameter not working

### ISSUE THREAD

**Issue by marshmn** [finanalyst/grav-plugin-sqlite#3]
Setting the `id` parameter on the shortcode is not working.

e.g.
```
[sql-table id=foo]
...
[/sql-table]
```

The above should result in setting the `id` attribute on the table to `foo` - but instead no `id` attribute is present in the output.

**Comment by marshmn** [comment]
I've created PR #4 with a fix for this issue.

**Comment by finanalyst** [comment]
I have just fixed another issue, included you in the credits in the README, and published a new release. Thanks again.

**Comment by marshmn** [comment]
On Wed, 19 Dec 2018, at 11:38, Richard Hainsworth wrote:
> I have just fixed another issue, included you in the credits in the README, and published a new release. Thanks again.



No problem. Thanks for getting a release out - saves me having to use a local version. 

Thanks also for the plugin - works really well!

Thanks,
Matt

-- 
*Matt Marsh*
matt@crazedbytes.net
+44 (0)7795 297779 <tel:+44-7795-297779>
