### ISSUE TITLE
How to list rows from table in HTML and edit any one of them without hardcoding ID in SQL?

### ISSUE THREAD

**Issue by covecove1** [finanalyst/grav-plugin-sqlite#5]
Hello,

I would like to ask you if it's possible to fetch all table rows and list them on a page by somehow looping trough them, and when we press button "Edit" on any of those items, to get correct row by it's ID to be changed? If so, how can I accomplish that? 💯 👍 :)

It yould be a pretty nice small alternative to some web app functionalities..

Thank you!

**Comment by finanalyst** [comment]
I have done this using my sqlite plugin and my datatables plugin. 
Since this is similar to another question I was asked, I have shown some working code to illustrate. See the item: [mutiple forms, sqlite and map](https://discourse.getgrav.org/t/multiple-forms-datatables-sqlite-and-map/8289)
