### ISSUE TITLE
Front Matter and Site Variables not recognized

### ISSUE THREAD

**Issue by asitemade4u** [finanalyst/grav-plugin-sqlite#7]
Hi,
Thank you for the plugin which is very useful to bridge a lot of gaps!
I am having an issue though.
NB. I am using the `chinook` database which is provided as a [test database](http://www.sqlitetutorial.net/sqlite-sample-database/) by SQLite
I am trying to include a front matter variable in the stanza, so that I may have a different one for each page.
Here is the code for the page:
```
---
title: 'Test Database'
template: places
database:
    query: "Smith"
shortcode-core:
    active: true
cache-enabled: false
process:
    twig: true
---
Query String: <strong>{{page.header.database.query}}</strong>

[sql-table]
SELECT  trackid, name, composer, milliseconds FROM tracks WHERE composer LIKE "{{page.header.database.query}}" ORDER BY trackid ASC LIMIT 10;
[/sql-table]
```

The outcome is that the query string `Smith` is well recognized on the page but is NOT within the stanza: it is left empty there. As a result the SQL query is executed on an empty string instead of `Smith` and yields no result. Have a look at the attached screenshot.
![20190227_10-03-38](https://user-images.githubusercontent.com/11460106/53499788-15a27b80-3a77-11e9-93fd-19be18b70486.png)

Please help.
Best,
Stephen

**Comment by asitemade4u** [comment]
Just for the record, I also tried to draw the variable from the `site.yaml` configuration file and the outcome is the same: recognized on the page, not recognized within the stanza.
Here is the code:
```
---
title: 'Test Database'
template: places
database:
    query: 'Smith'
shortcode-core:
    active: true
cache-enabled: false
process:
    twig: true
---

This is some database

Query String: <strong>{{page.header.database.query}}</strong>
Query String from Site: <strong>{{site.database.query}}</strong>

[sql-table]
SELECT  trackid, name, composer, milliseconds FROM tracks WHERE composer LIKE '{{site.database.query}}' ORDER BY trackid ASC LIMIT 10;
[/sql-table]
```

**Comment by asitemade4u** [comment]
Here is the execution log:
`
2019-02-27:09:53: SELECT trackid, name, composer, milliseconds FROM tracks WHERE composer LIKE "" ORDER BY trackid ASC LIMIT 10;
2019-02-27:09:53: SELECT trackid, name, composer, milliseconds FROM tracks WHERE composer LIKE "" ORDER BY trackid ASC LIMIT 10; `

**Comment by finanalyst** [comment]
@asitemade4u Very sincere apologies for such a long delay.

The issue is not in the plugin, but in timing between shortcode and page data. If you can find another plugin that does what you want, re-open this issue.
