### ISSUE TITLE
Plugin complains when I insert returns within the stanza

### ISSUE THREAD

**Issue by asitemade4u** [finanalyst/grav-plugin-sqlite#8]
As per your examples, one is allowed to insert carriage returns within the SQL stanza in order to make it more readable.
Unfortunately the plugin reports an error when doing so.
Best,
Stephen

**Comment by hughbris** [comment]
Not the repo maintainer, but thought this might be an easy fix. I could not reproduce it using a simple `SELECT` query with a line break.

Could you show us the query you are trying? What is the error you are seeing? Have you tried the query on command line (or in another Sqlite client application)?

_"the plugin reports an error"_ is a little vague and you will generally get better responses when you provide more detail.

**Comment by finanalyst** [comment]
No response to @hughbris  so closing this
